// ==++==
//
//   Copyright (c) LEI Hongfaan.  All rights reserved.  Licensed under the MIT License.
//
// ==--==
// ==++==
//
//   MIT License
//
//   Copyright (c) 2019 LEI Hongfaan
//
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//   of this software and associated documentation files (the "Software"), to deal
//   in the Software without restriction, including without limitation the rights
//   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//   copies of the Software, and to permit persons to whom the Software is
//   furnished to do so, subject to the following conditions:
//
//   The above copyright notice and this permission notice shall be included in all
//   copies or substantial portions of the Software.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//   SOFTWARE.
//
// ==--==
//----------------------
// <auto-generated>
//     Generated using T4 Template.
// </auto-generated>
//----------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace UltimateOrb.Functional.CommonDelegates {

    public static partial class CreateInstance {

        public static LambdaExpression GetExpression(Type? type) {
            if (type == null) {
                throw new ArgumentNullException(nameof(type));
            }
            return GetExpressionInternal(type);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T> GetValue<T>() {
            return GetValueInternal<T>();
        }

        public static Delegate GetValue(Type? type) {
            if (type == null) {
                throw new ArgumentNullException(nameof(type));
            }
            return GetValueInternal(type);
        }

        internal static LambdaExpression GetExpressionInternal(Type type) {
            // TODO: Cache the results.
            return GetExpressionInternalCore(type);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Func<T> GetValueInternal<T>() {
            return PerType<T>.Value;
        }

        internal static Delegate GetValueInternal(Type type) {
            return (typeof(PerType<>).MakeGenericType(type).GetField(nameof(PerType<VoidResult>.Value)).GetValue(null) as Delegate)!;
        }

        public static class PerType<T> {
            
			public static readonly Func<T> Value = GetValueCore();

            [MethodImpl(MethodImplOptions.NoInlining)]
            private static Func<T> GetValueCore() {
                return (GetValueInternalCore(typeof(T)) as Func<T>)!;
            }
        }
    }
}

namespace UltimateOrb.Functional.CommonDelegates {

    public static partial class CreateBoxedInstance {

        public static LambdaExpression GetExpression(Type? type) {
            if (type == null) {
                throw new ArgumentNullException(nameof(type));
            }
            return GetExpressionInternal(type);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<StrongBox<T>> GetValue<T>() {
            return GetValueInternal<T>();
        }

        public static Delegate GetValue(Type? type) {
            if (type == null) {
                throw new ArgumentNullException(nameof(type));
            }
            return GetValueInternal(type);
        }

        internal static LambdaExpression GetExpressionInternal(Type type) {
            // TODO: Cache the results.
            return GetExpressionInternalCore(type);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Func<StrongBox<T>> GetValueInternal<T>() {
            return PerType<T>.Value;
        }

        internal static Delegate GetValueInternal(Type type) {
            return (typeof(PerType<>).MakeGenericType(type).GetField(nameof(PerType<VoidResult>.Value)).GetValue(null) as Delegate)!;
        }

        public static class PerType<T> {
            
			public static readonly Func<StrongBox<T>> Value = GetValueCore();

            [MethodImpl(MethodImplOptions.NoInlining)]
            private static Func<StrongBox<T>> GetValueCore() {
                return (GetValueInternalCore(typeof(T)) as Func<StrongBox<T>>)!;
            }
        }
    }
}
